### ISSUE TITLE
ArgumentError: Python argument types in pyviennacl._viennacl.iterative_solve did not match C++ signature

### ISSUE THREAD

**Issue by abrahamneben** [viennacl/pyviennacl-dev#38] opened 2016-07-28 18:40 UTC
In trying to follow the example in http://viennacl.sourceforge.net/pyviennacl/doc/examples/iterative-solvers.html, I get this error:

**My code:**

```
import pyviennacl as p
import numpy as np
import os, random

A = p.Matrix(np.random.randn(10,10),dtype=np.float32)
b = p.Vector(np.ones(10,dtype=np.float32),dtype=np.float32)

tag = p.gmres_tag(tolerance = 1e-5, max_iterations = 150, krylov_dim = 50)
x = p.solve(A, b, tag)
```

ArgumentError                             Traceback (most recent call last)
<ipython-input-62-95e4416c2ce8> in <module>()
      1 # Solve the system
----> 2 x = p.solve(A, b, tag)

/Users/abrahamneben/.pyenv/versions/chips-3.4.3/lib/python3.4/site-packages/pyviennacl/linalg.py in solve(A, B, tag, precond)
    472                                layout = B.layout)
    473         else:
--> 474             return result_type(tag.vcl_solve_call(A.vcl_leaf, B.vcl_leaf, tag.vcl_tag),
    475                                dtype = B.dtype,
    476                                layout = B.layout)

/Users/abrahamneben/.pyenv/versions/chips-3.4.3/lib/python3.4/site-packages/pyviennacl/linalg.py in vcl_solve_call(self, _args)
    175     """
    176     def vcl_solve_call(self, *args):
--> 177         return _v.iterative_solve(_args)
    178 
    179     def **init**(self,tolerance = 1e-8, max_iterations = 300, krylov_dim = 20):

ArgumentError: Python argument types in
    pyviennacl._viennacl.iterative_solve(matrix_row_float, vector_float, gmres_tag)
did not match C++ signature:
    iterative_solve(viennacl::hyb_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::hyb_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::hyb_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<double, 128u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<double, 128u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<double, 128u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<double, 1u> {lvalue}, viennacl::vector<double, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::hyb_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::hyb_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::hyb_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::ell_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<float, 128u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<float, 128u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::coordinate_matrix<float, 128u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::gmres_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::bicgstab_tag {lvalue})
    iterative_solve(viennacl::compressed_matrix<float, 1u> {lvalue}, viennacl::vector<float, 1u> {lvalue}, viennacl::linalg::cg_tag {lvalue})

**Comment by tsmithe** [comment] 2016-07-28 18:45
This looks to be a duplicate of issue #32. Unfortunately, I have been very busy with my studies for a couple of years, and so PyViennaCL has rather suffered. You might try the version in git, but it is still quite out of date, and I haven't kept it in sync with ViennaCL development for a while.. I am very sorry about this, and I hope one day to return to fix this, but in the short term I am not particularly hopeful.

**Closed as completed by tsmithe** 2016-07-28 18:45 UTC

**Comment by abrahamneben** [comment] 2016-07-28 18:53
BTW, @tsmithe  I installed this using pip

**Comment by tsmithe** [comment] 2016-07-28 18:54
Yes, that will give you the last stable release, which is behind the git version (which itself is mostly stable, though not receiving new development at the moment).
